spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
server:
  address: 0.0.0.0
  forward-headers-strategy: framework
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
