spring:
  application:
    name: cravewallet-backend
  profiles:
    default: local
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
server:
  port: ${PORT:8080}
  error:
    include-message: never
    include-stacktrace: never
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
springdoc:
  swagger-ui:
    path: /swagger-ui.html
